name: CI
on:
  pull_request:
    branches: [development]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '14.17.x'
      - run: yarn install --immutable --immutable-cache --check-cache
      - run: yarn format:check
      - run: yarn test -- --coverage
        env:
          CI: true
