name: CI
on:
  pull_request:
    branches: [development]
  push:
    branches: [development]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '14.17.x'
      - run: yarn install --immutable --immutable-cache --check-cache
      - run: yarn format:check
      - run: yarn test -- --coverage
        env:
          CI: true
      - name: Build Project
        if: github.event_name == 'push'
        run: yarn build
      - name: Deploy to Staging
        if: github.event_name == 'push'
        run: npx surge --project ./build --domain spotless-ghost.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
